# Generated by Django 5.0.2 on 2024-02-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('meters', 'Meters'), ('dozen', 'Dozens')], default='pieces', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
